### PR TITLE
Fixes issue #5445: Scheduled query not working

### LINKED ISSUE #5445: Scheduled query not working in the latest preview Docker Image (redash/redash:preview)
### Issue Summary

Scheduled query not working in the latest preview Docker Image (redash/redash:preview).

### Steps to Reproduce

`redash_scheduled_worker_1` has error:

```
[2021-03-27 07:27:06,319][PID:520][ERROR][rq.worker] AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 934, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 686, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 692, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/redash/tasks/queries/execution.py", line 288, in execute_query
    scheduled_query_id is not None,
  File "/app/redash/tasks/queries/execution.py", line 175, in __init__
    models.scheduled_queries_executions.update(self.query_model.id)
AttributeError: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 934, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 686, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 692, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/app/redash/tasks/queries/execution.py", line 288, in execute_query
    scheduled_query_id is not None,
  File "/app/redash/tasks/queries/execution.py", line 175, in __init__
    models.scheduled_queries_executions.update(self.query_model.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

If I revert this commit (9fdf1f341d02d903f045ea65d130a3cc93884299), it works again.

### Technical details:

* Redash Version: Version: 9.0.0-beta (44178d99)
* Browser/OS: Chrome
* How did you install Redash: Docker

### PR DESCRIPTION
**Pull request by susodapop**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

After #5394 scheduled queries fail to execute. But all the unit tests pass. I'm not sure what's causing this, but I can fix it with the code change in this PR. I'd still like to add a unit test for this behavior.

## Related Tickets & Documents

Closes #5445 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

N/A

### CODE REVIEW

**Comment by rauchy** [comment]
Thanks @susodapop, a few notes:

1. Whoops! I forgot to backport one key change which is to send in a `query_id` [instead of `Query ID`](https://github.com/getredash/redash/blob/master/redash/tasks/queries/maintenance.py#L99) during query refreshes.
2. The reason this was not caught in tests is that our refresh query test expectations were too low on the shape of `metadata`. I'm not a big fan of using `metadata` for this, but the idea was to remain backward compatible for now (at least until we redesign our scheduler).
3. I went ahead and changed all `"Query ID"` to `"query_id"` everywhere and added it to this PR, as well as some tests modifications to handle this.
4. I think your commit may have prevented the scheduler from blowing up, but I'm pretty sure it silenced a problem that will later happen with locks, so I went ahead and reverted it.

**Review by susodapop — COMMENTED** [review]
LGTM 👍
