### ISSUE TITLE
`ImportError: cannot import name wraps` error occurs when execute pytest in localhost.

### ISSUE THREAD

**Issue by bamboo-yujiro** [getredash/redash#2176]
After I faced this probrem, saw below link and downgrade version of `mock` to `1.0.1` and could execute pytest.
https://stackoverflow.com/questions/31417964/importerror-cannot-import-name-wraps

In your `requirements_dev.txt`, described as `mock==2.0.0`, but even if this way, is it possible to run pytest?

**Before:**
<img width="1259" alt="mock1" src="https://user-images.githubusercontent.com/8569015/34255596-c5163da0-e694-11e7-8a45-5198228aee54.png">

**After:**
<img width="1276" alt="mock2" src="https://user-images.githubusercontent.com/8569015/34255606-caaf3ece-e694-11e7-9182-369634903b5d.png">

### Issue Summary

As above.

### Steps to Reproduce

1. `$ pip install -r requirements.txt -r requirements_dev.txt`
2. `$ bin/run pytest tests/`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

=> Development Environment is so important to any engineers  as you know in order to improve redash more and more.
So, I want to make it more confortable!

### Technical details:

* Redash Version: 4.0.0
* Browser/OS: Mac osx 
* How did you install Redash: `git clone, docker compose, pip install`

**Comment by arikfr** [comment]
When I run tests via Docker it works with `mock==2.0.0`. The answer to the StackOverflow question you linked to mentions that it might be an issue with outdated setuptools version. Can you make sure you have updated version of those and try installing requirements again?

I prefer to use recent dependencies versions when possible.

**Comment by bamboo-yujiro** [comment]
@arikfr
Thanks for your comment.
After I investigated, noticed that old version of `six` in System on OSX was referenced.
Here is the reference link. 
https://stackoverflow.com/questions/36073263/importerror-cannot-import-name-wraps-on-mac

I installed Python 2.7.x via `pyenv`, and manage Libraries in there and I could execute `pytest`. 
Sorry for the confusion. :sweat_smile:
