### ISSUE TITLE
pymssql 2.1.3 is needed for Re:dash 0.12

### ISSUE THREAD

**Issue by kitsuyui** [getredash/redash#1205]
### Issue Summary

- recently added configuration of tds_version. (https://github.com/getredash/redash/pull/1151)
- But, its feature is available from v2.1.3 (https://github.com/pymssql/pymssql/releases/tag/v2.1.3, https://github.com/pymssql/pymssql/commit/999e0d950e7bd1b5b2330ce28563d1bfe2c16ef0)
- And yet version is v2.1.2 (https://github.com/getredash/redash/blob/master/requirements_all_ds.txt#L12)
- So an error will occur.

### Steps to Reproduce

1. Install Re:dash 0.12.0+b2068 (with setup/ubuntu/bootstrap.sh)
2. Add SQL Server settings to data source.
3. Execute some query,  e.g.  `SELECT 1`
4. Get an error. (in `/opt/redash/logs/celery_error.log`)

```
raised unexpected: TypeError("connect() got an unexpected keyword argument 'tds_version'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2068/redash/tasks/base.py", line 13, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2068/redash/tasks/queries.py", line 440, in execute_query
    return QueryExecutor(self, query, data_source_id, metadata).run()
  File "/opt/redash/redash.0.12.0.b2068/redash/tasks/queries.py", line 390, in run
    data, error = query_runner.run_query(annotated_query)
  File "/opt/redash/redash.0.12.0.b2068/redash/query_runner/mssql.py", line 133, in run_query
    connection = pymssql.connect(server=server, user=user, password=password, database=db, tds_version=tds_version, charset=charset)
  File "pymssql.pyx", line 579, in pymssql.connect (pymssql.c:9097)
TypeError: connect() got an unexpected keyword argument 'tds_version'
```

### Technical details:

* Redash Version: Re:dash 0.12.0+b2068
* Browser/OS: Google Chrome 51.0.2704.106, OS X 10.11.6, Ubuntu 16.04 LTS
* How did you install Redash: setup/ubuntu/bootstrap.sh

**Comment by JoshKeegan** [comment]
For anyone that comes accross this when upgrading to 0.12 from a previous version, the upgrade script doesn't do this, so it has to be done manually.
That's dead simple, just:
```
pip install pymssql --upgrade
```
Followed by a reboot.
