### PR TITLE
Fix Elasticsearch query runner error: 'str' object has no attribute 'pop' error when parsing query

### PR DESCRIPTION
**Pull request by jcowley**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
Fix Elasticsearch query runner (refactored version not yet released)

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

I needed redash to work with elasticsearch 7.10, but the current v10.1.0 release does not support it. There was a major refactor of the elasticsearch query runner in #5794, but that code has not yet been released. So, I got the latest from master and tried it out.

I'm not sure how this code was tested originally, but it doesn't work because of a very minor bug. When building the elasticsearch query, it's trying to call `pop()` on the `query` parameter which is of type `str`, and there is no `pop()` method on `str`. Any attempt to run an elasticsearch query results in the error:

`'str' object has no attribute 'pop' error when parsing query`

It needs to be converted to a dictionary, which is a one line change. Then it works fine.

Not sure how this wasn't caught earlier. Maybe no one has tried it out yet? I do appreciate all the hard work that @NicolasLM, @susodapop, and @wwl717195673 put into the refactor. It's been working well for us after this fix.

## Related Tickets & Documents
#5794

### CODE REVIEW

**Review by AndrewChubatiuk — APPROVED** [review]
LGTM

**Comment by justinclift** [comment]
Thanks @AndrewChubatiuk. :smile:

**Review by justinclift — APPROVED** [review]
Looks straight forward enough, and @AndrewChubatiuk didn't spot anything wrong. :smile:

**Comment by justinclift** [comment]
@jcowley Thanks for spotting this, and fixing it. :smile:

**Comment by jcowley** [comment]
No problem. Thanks for getting it merged in.
