### ISSUE TITLE
after updating to  2.0  fail  Query Excecution 

### ISSUE THREAD

**Issue by HiuNaoki** [getredash/redash#1962]
### Issue Summary

after updating to 2.0   then display below message   if runing query to BigQuery 

"Error running query: 'NoneType' object has no attribute 'annotate_query'"

### Steps to Reproduce

1. 
undating redash 1.0 to 2.0   
https://redash.io/help-onpremise/maintenance/how-to-upgrade-redash.html

2. This is the second step, etc.
upgrade for python package  for instruntion

sudo pip install -U google-api-python-client==1.5.1
sudo pip install -U oauth2client==3.0.0

and restart  redash
sudo supervisorctl restart redash_server

3. 
Data Source for BQ is connection Succesfull
but if running query   show below message 
"Error running query: 'NoneType' object has no attribute 'annotate_query'"

### Technical details:

* Redash Version: 2.0
* Browser/OS: Chrome/ubuntu
* How did you install Redash:  AWS  ami

regurd

**Comment by FabricioFFC** [comment]
@HiuNaoki I was having the same issue. I solved it restarting all processes: `sudo supervisorctl restart all`

**Comment by HiuNaoki** [comment]
@FabricioFFC  thank you!
